// <auto-generated />
namespace Jop_Offers_Website.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class editJobModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editJobModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202201281727083_editJobModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
